[FEATURE] implement firstCategory property
FriendsOfTYPO3/tt_address pull request #383
Opened 2021-11-24 15:14 UTC by h3nn3s

With having a firstCategory property, it would easyly possible
to implement a grouping by category in Fluid -
e.g. for a category based accordeon.

Resolves: #382

2021-12-07 09:06 UTC, georgringer requested changes

2021-12-07 09:06 UTC, georgringer commented on Classes/Domain/Model/Address.php
> +    public function getFirstCategory()
please add return type + also nullable

2021-12-07 09:06 UTC, georgringer commented on Classes/Domain/Model/Address.php
> +     * @return \TYPO3\CMS\Extbase\Domain\Model\Category
also null is possible

2021-12-07 09:06 UTC, georgringer commented on Documentation/Tutorials/Templates/GroupAddressRecords/Index.rst
> +				<f:groupedFor each="{addresses}" as="groupedAddresses" groupBy="firstCategory" groupKey="cat">
change cat to category, no need to save chars

2022-01-06 07:45 UTC, h3nn3s commented
Thanks for reviewing, Georg

2022-01-12 12:55 UTC, georgringer approved these changes

2022-01-12 13:05 UTC, merged